### ISSUE TITLE
First Run is slow

### ISSUE THREAD

**Issue by JeffBusterCase** [Nyerst/FastGenericNew#16] opened 2022-03-13 13:06 UTC

**Comment by Nyerst** [comment] 2022-03-13 14:10
Hi. thanks for the comment.

In most cases, we can only choose one of first-run speed and post-run speed on a managed platform.
However. using ILEmit instead of Expression can shorten the first run time a bit.
But this will need an overhaul of the entire library.

I'll try it tomorrow.

**Comment by JeffBusterCase** [comment] 2022-03-13 16:35
Maybe adding a Initialization? I don't know if this is possible.... Before a project is run.?

**Comment by Nyerst** [comment] 2022-03-14 09:30
> Maybe adding a Initialization? I don't know if this is possible.... Before a project is run.?

I think it can't be a solution.
You just moved that 1ms to elsewhere but it won't change the fact that it took 1ms.

**Comment by JeffBusterCase** [comment] 2022-03-15 00:11
Man..., I don't it serves it purpose if it needs to gen the method for teach different class/struct...
![image](https://user-images.githubusercontent.com/12688410/158281040-f5736579-9cd1-4e33-9b07-9fcbbf14e6bb.png)

What I think if it's what you mentioned before, is, when the application in initialized, FastNew needs to generate All possible class/struct use cases. So there will really be a performance gain when used.

**Comment by JeffBusterCase** [comment] 2022-03-15 00:40
This one displays the ~sad~ gap even more:
![image](https://user-images.githubusercontent.com/12688410/158283616-953f7b25-acfc-4a91-84f0-2ea6abdc2a7b.png)

**Comment by Nyerst** [comment] 2022-03-15 01:19
> This one displays the ~sad~ gap even more: ![image](https://user-images.githubusercontent.com/12688410/158283616-953f7b25-acfc-4a91-84f0-2ea6abdc2a7b.png)

Can you provide the source code so I can reproduce this?

**Comment by JeffBusterCase** [comment] 2022-03-15 02:05
Here:
https://github.com/JeffBusterCase/BenchmarkFastNewManually

**Comment by Nyerst** [comment] 2022-03-15 02:42
> Here: [JeffBusterCase/BenchmarkFastNewManually](https://github.com/JeffBusterCase/BenchmarkFastNewManually)

Thanks. I see the code and I think there are some issues with the measuring.

First, you shouldn't benchmark them in parallel. 
It's because two or more threads can be assigned to the same CPU core and they will be certainly slower than others.
You should benchmark them one by one instead.

And you should use `Stopwatch` instead of `DateTime`.

> Stopwatch automatically checks for the existence of high-precision timers.
>It is worth mentioning that DateTime.Now often is quite a bit slower than DateTime.UtcNow due to the work that has to be done with timezones, [DST](http://en.wikipedia.org/wiki/Daylight_saving_time) and such.
>DateTime.UtcNow typically has a resolution of 15 ms. See [John Chapman's blog post](http://jaychapman.blogspot.com/2007/12/datetimenow-precision-issues-enter.html) about DateTime.Now precision for a great summary.

https://stackoverflow.com/questions/28637/is-datetime-now-the-best-way-to-measure-a-functions-performance

It's recommended to use Benchmark.NET
https://benchmarkdotnet.org/articles/overview.html

**Comment by JeffBusterCase** [comment] 2022-03-15 03:20
I updated the code to better match the correct benchmark, but still... the initialization is what kills the objective :(
https://github.com/JeffBusterCase/BenchmarkFastNewManually
![image](https://user-images.githubusercontent.com/12688410/158299278-545476c8-57ca-4a1a-85d6-7356ccb58ddd.png)

**Comment by Nyerst** [comment] 2022-03-18 06:51
This issue is delayed to 3.2.0 due I found a solution that better than ILGenerator.
It will be started in another branch.

**Closed** 2022-03-22 08:25 UTC
Labels: enhancement

**Comment by Nyerst** [comment] 2022-03-22 08:28
Solved in #19 
you can enable FastGenericNew.SourceGenerator to call `GetActivationInfo` by adding this to the project file

```xml
<PropertyGroup>
    <FastNew_AllowUnsafeImplementation>true</FastNew_AllowUnsafeImplementation>
</PropertyGroup>
```

**Comment by JeffBusterCase** [comment] 2022-03-22 10:24
Sorry, I didn't understand.. Shouldn't this be a 'official' fix instead of a workaround/option.....
How can I test on my project witthout the Nuget Version (Still on 3.1.0-preview)

**Comment by Nyerst** [comment] 2022-03-22 11:22
> Sorry, I didn't understand.. Shouldn't this be a 'official' fix instead of a workaround/option..... How can I test on my project witthout the Nuget Version (Still on 3.1.0-preview)

This is an 'official' fix. the new implementation is stable now after working on it.
You can see how this library work now by checking the generated code: https://github.com/Nyerst/FastGenericNew/tree/main/FastGenericNew/_generated/FastGenericNew.SourceGenerator/FastGenericNew.SourceGenerator.Generator

The reason why this is an option is that it's slower than the classic FastNew
which defeats the purpose of this library

v3.2.0 is not released yet because there are still some minor jobs for the Unit Test project to do.
For now, you can try v3.2.0 by cloning this repo and compiling it.
Note that you will need .NET 7 SDK to compile this library.

You can reproduce the Benchmark by running the FastGenericNew.Benchmarks project.
